import {
  Image,
  Layers,
  Droplets,
  Maximize2,
  Network,
  Plus,
  Grid3x3,
  Package,
  GitMerge,
  Zap,
  GitBranch,
  Target,
  BookOpen,
} from "lucide-react";

export const FIELD_LABEL_MAP: Record<string, string> = {
  outputShape: "输出形状",
  filters: "卷积核数量",
  kernelSize: "卷积核大小",
  stride: "步长",
  padding: "填充",
  poolSize: "池化窗口",
  rate: "丢弃率",
  numFeatures: "特征数量",
  normType: "归一化类型",
  type: "类型",
  dimension: "嵌入维度",
  numHeads: "注意力头数",
  headDim: "单头维度",
  modelDim: "模型维度",
  dropout: "Dropout",
  activation: "激活函数",
};

export const ICON_MAP: Record<string, any> = {
  input: Image,
  conv2d: Layers,
  maxpool2d: Droplets,
  avgpool2d: Droplets,
  adaptiveavgpool2d: Droplets,
  flatten: Maximize2,
  linear: Network,
  embedding: BookOpen,
  dropout: Grid3x3,
  batchnorm: Layers,
  batchnorm2d: Layers,
  layernorm: Layers,
  lrn: Layers,
  relu: Zap,
  sigmoid: Zap,
  tanh: Zap,
  softmax: Zap,
  add: Plus,
  concat: GitMerge,
  sequential: Package,
  parallel: GitBranch,
  "self-attention": Target,
  "cross-attention": Target,
};

export const NODE_TYPE_NAMES: Record<string, string> = {
  input: "输入层",
  embedding: "嵌入层",
  flatten: "展平层",
  linear: "全连接层",
  conv2d: "卷积层",
  maxpool2d: "最大池化",
  avgpool2d: "平均池化",
  adaptiveavgpool2d: "自适应池化",
  batchnorm: "批归一化",
  layernorm: "层归一化",
  lrn: "局部响应归一化",
  relu: "ReLU",
  sigmoid: "Sigmoid",
  tanh: "Tanh",
  softmax: "Softmax",
  dropout: "Dropout",
  add: "加法",
  concat: "拼接",
  sequential: "顺序模块",
  parallel: "并行模块",
  "self-attention": "自注意力",
  "cross-attention": "交叉注意力",
};


